### ISSUE TITLE
Not running with .NET 5.0

### ISSUE THREAD

**Issue by nesc58** [gmarokov/dotnet-trx2sonar#1]
Hi,
i am unable to use this great tool with dotnet sdk 5.0.202

I am not familiar with github actions, so I have no idea how to solve the problem.

The only thing I can add is these:
The line in .csproj must be changed from
```
<TargetFramework>netcoreapp3.1</TargetFramework>
```
to
```
<TargetFrameworks>netcoreapp3.1;net50</TargetFrameworks>
```

Log:
```
dotnet-trx2sonar -d . -o ./TestResults/sonartestresults.xml
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
- The following frameworks were found:
     5.0.5 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
````

**Comment by gmarokov** [comment]
Hey @nesc58, both PRs are closed now, thanks for that. I hope to push a release any time soon. Closing as resolved
